export const data = [
  {
    recipeName: "Belugalinsen Curry",
    thumbnail: "https://picsum.photos/id/292/200/300",
    duration: 10,
    ingredients: ["x"],
    steps: ["x"],
  },
  {
    recipeName: "Cremiger Dinkel mit Tomaten",
    thumbnail: "https://picsum.photos/id/225/200/300",
    duration: 20,
    ingredients: [
      "300g Dinkel",
      "2 Zehen Knoblauch",
      "8 Rispentomaten",
      "1 Zucchini",
      "1 Zwiebel",
      "1 Handvoll getrocknete Tomaten",
      "250g Joghurt (alternativ 100g Frischkäse)",
      "50g Feta",
      "Petersilie",
    ],
    steps: [
      "1. Dinkel ca. 30min in Salzwasser kochen.",
      "2. Rispentomaten und getrocknete Tomaten schneiden, Feta würfeln.",
      "3. Zwiebel, Knoblauch und Gemüse in einer Pfanne anbraten. Dinkel abgießen, in die Pfanne geben und etwas mitbraten. Getrockenete Tomaten hinzufügen.",
      "4. Joghurt und Feta mit in die Pfanne geben. Aufkochen lassen und nach Belieben würzen.",
    ],
  },
  {
    recipeName: "Linsen-Lasagne",
    thumbnail: "https://picsum.photos/id/425/200/300",
    duration: 30,
    ingredients: [
      "1 Tasse rote Linsen",
      "500g Tomaten",
      "2 EL Tomatenmark",
      "2 kleine Frühlingszwiebeln",
      "1 Zwiebel",
      "2 Zehen Knoblauch",
      "2 Schuss Sojasoße",
      "Gemüsebrühe",
      "Sambal Olek",
      "Lasagneplatten",
      "Bechamelsoße: 25g Butter, 25g Mehl, 250-300ml Milch, Salz, Pfeffer, Muskat",
    ],
    steps: [
      "1. Zunächst die roten Linsen nach Packungsanleitung in ca. 1 Liter Wasser kochen. Anschließend die Linsen durch ein Sieb abgießen und abtropfen lassen. Eventuell mit einem Löffel etwas ausdrücken.",
      "2. Die Frühlingszwiebeln, Schalotte und Knoblauchzehen hacken und mit Öl in einer Pfanne glasig anschwitzen. Die roten Linsen hinzugeben und kurz anbraten.",
      "3. Dann die passierten Tomaten und das Tomatenmark hinzugeben. Mit Salz, Pfeffer, Basilikum, Oregano, Paprikapulver, Tabasco/Chiliflocken, Sambal Olek und etwas Sojasoße würzen. Kurz aufkochen lassen. Darauf achten, dass genügend Flüssigkeit vorhanden ist (noch Gemüsebrühe hinzu).",
      "4. Die Auflaufform mit Öl/ Margarine einfetten und den Ofen auf ca. 200°C vorheizen.",
      "5. Bechamelsoße zubereiten und diese ca. 5min köcheln lassen.",
      "6. Nun abwechselnd Lasagneplatten und Linsenbolognese in die Auflaufform schichten. Ganz zuoberst die Bechamelsoße gießen.",
      "7. Für ca. 25 – 30 min in den Ofen.",
    ],
  },
  {
    recipeName: "Bircher Müsli",
    thumbnail: "https://picsum.photos/id/493/200/300",
    duration: 10,
    ingredients: [
      "100g Frucht",
      "20g Nüsse",
      "50g Haferflocken",
      "20g Rosinen",
      "200ml Pflanzendrink",
      "1 Prise Salz",
      "1/2 TL Zimt",
    ],
    steps: [
      "1. Frucht in kleine Stückchen schneiden. Nüsse grob hacken.",
      "2. Beides in eine Schale geben. Mit Haferflocken, Rosinen und dem Pflanzendrink mischen.",
      "3. Salz und Zimt hinzugeben.",
      "4. Für mind. 3h in den Kühlschrank (besser über Nacht).",
    ],
  },
];
